const express = require("express");
const router = express.Router();
const productController = require("../controllers/product.controller");
const { visitorCounter } = require("../middleware/visitorCounter");
router.post("/", productController.createProduct);
router.get("/", productController.getProducts);
router.get("/:id",visitorCounter, productController.getProductById);
router.patch("/:id", productController.updateProduct);
router.delete("/:id", productController.deleteProduct);
module.exports = router;
